### ISSUE TITLE
The following reports does not work on mmex v1.2.0+

### ISSUE THREAD

**Issue by asokareddy** [moneymanagerex/general-reports#31]
BudgetMonitoringCurrentMonth
BudgetMonitoringLastMonth
CategoriesStatLast12Months
CategoryForecast
CategoryTrend

The charts are created using the javascript framework ChartJS from 
http://chartjs.devexpress.com/, which creates simply 
stunning gauge widgets. 
and copy the following three files from the archive directory Lib/js directly 
into your MoneyManagerEx/res 
dx.chartjs.
jquery-2.0.3.min.
globalize.min.js

**Comment by vomikan** [comment]
Just the week ago I've updated the ![CategoriesStatLast12Months](https://github.com/moneymanagerex/general-reports/tree/master/CategoriesStatLast12Months) report.
It works.

**Comment by siowena** [comment]
The reports listed have been updated to use the latest from devexpress as the filenames changed. The reports work on v1.3.3 and suggest @asokareddy updates to the latest full release.

@guanlisheng - Suggest this Issue is now closed.

(from Pull request #59)
BudgetMonitoringCurrentMonth & BudgetMonitoringLastMonth
- changed the scripts libraries to use the latest from http://chartjs.devexpress.com/Download
(dx.viz-web.js, jquery-2.0.3.min.js, jquery.min.js) as the older files are no longer available
